### ISSUE TITLE
ES, kibana와 연동

### ISSUE THREAD

**Issue by Seongbeom-Park** [AllBackEnd/school_assignment#12]
생성된 데이터를 키바나에서 볼 수 있도록 설정

**Comment by Seongbeom-Park** [comment]
database가 local일 경우 kibana에서 확인이 불가능함

**Comment by Seongbeom-Park** [comment]
```
# application.yml
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/school_assignment
```

**Comment by Seongbeom-Park** [comment]
```
# application.yml
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/school_assignment
```
